Tutorial Web/ViewModels/HomeIndexViewModel.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Tutorial_Web.ViewModels
{
    public class HomeIndexViewModel
    {
        //public int Id { get; set; }
        //public string Name { get; set; }
        //public int Age { get; set; }


        public IEnumerable<StudentViewModel> Students { get; set; }
    }
}

Tutorial Web/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;    

namespace Tutorial_Web.ViewModels
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "用户名")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "密码")]
        public string Password { get; set; }
    }
}

Tutorial Web/ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Tutorial_Web.ViewModels
{
    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "用户名")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "密码")]
        public string Password { get; set; }
    }
}

Tutorial Web/ViewModels/StudentViewModel.cs
 namespace Tutorial_Web.ViewModels
{
    public class StudentViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
    }
}

Tutorial Web/Controllers/AccountController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Tutorial_Web.ViewModels;

namespace Tutorial_Web.Controllers
{
    public class AccountController:Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;

        public AccountController
        (SignInManager<IdentityUser> signInManager,
            UserManager<IdentityUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel loginViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(loginViewModel);
            }

            var user = await _userManager.FindByNameAsync(loginViewModel.UserName);
            if (user!=null)
            {
                var result = await _signInManager.PasswordSignInAsync(user, loginViewModel.Password, false, false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            ModelState.AddModelError("", "密码不正确");
            return View(loginViewModel);
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel registerViewModel)
        {
            if (ModelState.IsValid)
            {
                var user =new IdentityUser
                {
                    UserName = registerViewModel.UserName
                };

                var result = await _userManager.CreateAsync(user, registerViewModel.Password);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            return View(registerViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

    }
}

Tutorial Web/Controllers/HomeController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Tutorial_Web.Model;
using Tutorial_Web.Services;
using Tutorial_Web.ViewModels;

namespace Tutorial_Web.Controllers
{

    public class HomeController : Controller
    {
        private readonly IRepository<Student> _repository;

        public HomeController(IRepository<Student> repository)
        {
            _repository = repository;
        }
        public IActionResult Index()
        {
            //            var name= this.ControllerContext.ActionDescriptor.ControllerName;
            // return this.Content("Hello From HomeController");

            #region Check3

            //var vt = new Student()
            //{
            //    Id = 1,
            //    FirstName = "Hex",
            //    LastName = "sola"
            //};
            ////return  new ObjectResult(vt);
            //return View(vt);

            #endregion

            var list = _repository.GetAll();//entity Model=>view model
            var vms = list.Select(x => new StudentViewModel()
            {
                Id = x.Id,
                Name = $"{x.FirstName}{x.LastName}",
                Age = DateTime.Now.Subtract(x.BirthDate).Days / 365
            });
            var vm = new HomeIndexViewModel
            {
                Students = vms
            };
            return View(vm);
        }

        public IActionResult Detail(int id)//路由
        {
            var student = _repository.GetById(id);
            if (student == null)
                return RedirectToAction(nameof(Index));

            return View(student);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken ]
        public IActionResult Create(StudentCenderModel student)
        {
            if (ModelState.IsValid)
            {
                var newStudent = new Student //页面传过来的值，新的内容
                {
                    FirstName = student.FirstName,
                    LastName = student.LastName,
                    BirthDate = student.BirthDate,
                    Gender = student.Gender

                };
                var newMedel = _repository.Add(newStudent);
                return RedirectToAction(nameof(Detail), new { id = newMedel.Id });
            }
            ModelState.AddModelError(string.Empty,"model lever Error!");
           
                return View();


        }
    }
}

Tutorial Web/ViewComponent/WelcomeViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Razor.Compilation;
using Tutorial_Web.Model;
using Tutorial_Web.Services;


namespace Tutorial_Web.ViewComponent
{
    public class WelcomeViewComponent:Microsoft.AspNetCore.Mvc.ViewComponent
    {
        private readonly IRepository<Student> _repository;

        public WelcomeViewComponent(IRepository<Student> repository)
        {
            _repository = repository;
        }

        public IViewComponentResult Invoke()
        {
            var count = _repository.GetAll().Count().ToString();
            return View("Default",count);
        }

    }
}

Tutorial Web/Views/Home/Create.cshtml
@using Tutorial_Web.Model
@model StudentCenderModel


<h1>创建学生</h1>

<form method="post">
    
    @*<input type="text" name="FirstName" value=""/>*@
    
    <div>
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName"/>
        <span asp-validation-for="FirstName"></span>
    </div>
    <div>
        <label asp-for="LastName"></label>
        <input asp-for="LastName" /> 
        <span asp-validation-for="LastName"></span>
    </div>
    <div>
        <label asp-for="BirthDate"></label>
        <input asp-for="BirthDate" type="date" />
        <span asp-validation-for="BirthDate"></span>
    </div>
    
    <div>
        <label asp-for="Gender"></label>
        <select asp-for="Gender" asp-items="Html.GetEnumSelectList<Gender>()"></select>
        <span asp-validation-for="Gender"></span>
    </div>
    
    <div asp-validation-summary="ModelOnly"></div>

    <div>
        <button type="submit" name="save">submit</button>
    </div>
    
</form>

Tutorial Web/Views/Home/Detail.cshtml
@model Tutorial_Web.Model.Student

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Detail</title>
</head>
<body>
<div>
    <h1>Student Message </h1>
    <div>ID:@Model.Id</div>
    <div>
        Name:@Model.FirstName  @Model.LastName
    </div>
    <div>
        Sex:@Model.Gender
    </div>
    <div>
        Birthday:@Model.BirthDate
    </div>
    <a asp-action="Index">Balck to home</a>
    
</div>
</body>
</html>

Tutorial Web/Views/Home/Index.cshtml
@*@model IEnumerable<Tutorial_Web.Model.Student>*@
@*@model IEnumerable<Tutorial_Web.ViewModels.HomeIndexViewModel>*@

@model HomeIndexViewModel

@{
    ViewBag.Title = "Home Index";

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Hello From Index.cshtml!!!</title>
</head>
<body>
<h1>Hello From Index.cshtml!!</h1>

<h2>Students</h2>


@*@Html.Partial("_StudentTable", Model.Students)*@

<partial name="_StudentTable" for="Students"/>





@section bottom
{
    <div>
        <a asp-action="Create">添加一个学生</a>
    </div>
}



</body>
</html>

Tutorial Web/Views/Home/_StudentRow.cshtml
@model StudentViewModel
<tr>
    <td>@Model.Name</td>
    <td>@Model.Age</td>
</tr>

Tutorial Web/Views/Home/_StudentTable.cshtml
@model IEnumerable<StudentViewModel>

<table>
    <thead>
    <tr>
        <td>姓名</td>
        <td>年龄</td>
    </tr>
    </thead>
    @foreach (var s in Model)
    {
        <partial name="_StudentRow" for="@s"/>
    }

</table>

Tutorial Web/Views/Shared/Components/Welcome/Default.cshtml
@model string

<h1>学生总数：@Model</h1>

Tutorial Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>

@inject SignInManager<IdentityUser> SignInManager


    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>

        <environment include="Development">
            <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        </environment>
        <environment exclude="Development">
            <link href="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/css/bootstrap.css"
                  asp-fallback-href="~/node_modules/bootstrap/dist/css/bootstrap.css"
                  asp-fallback-test-class="sr-only"
                  asp-fallback-test-property="position"
                  asp-fallback-test-value="absolute" />

        </environment>


    </head>
    <body>
        <h1>Tutorial Web</h1>
        <nav class="navbar navbar-light bg-light">
            <span class="navbar-brand mb-0 h1">Navbar</span>



            @if (SignInManager.IsSignedIn(User))
            {
                <form asp-action="Logout" asp-controller="Account" method="post" id="logoutForm">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a href="javascript:document.getElementById('logoutForm').submit()">登出</a>
                        </li>
                    </ul>
                </form>
            }
            else
            {
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a asp-action="Register" asp-controller="Account">注册</a>
                    </li>

                    <li class="nav-item">
                        <a asp-action="Login" asp-controller="Account">登陆</a>
                    </li>
                </ul>
            }




        </nav>

        <div>
            @RenderBody()
        </div>
        <hr />

        <div>
            @RenderSection("bottom", false)
        </div>

        @*@await Component.InvokeAsync("Welcome")*@
        <vc:welcome></vc:welcome>


        <environment include="Development">
            <script src="~/node_modules/jquery/dist/jquery.js"></script>
            <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
            <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
        </environment>


        <environment exclude="Development">
            <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/node_modules/jquery/dist/jquery.js"
                    asp-fallback-test="Windows.jQuery"></script>

            <script src="https://cdn.bootcss.com/jquery-validate/1.19.0/jquery.validate.min.js"
                    asp-fallback-src="~/node_modules/jquery-validation/dist/jquery.validate.js"
                    asp-fallback-test="Windows.jQuery&& Windows.jQuery.validate"></script>

            <script src="https://cdn.bootcss.com/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"
                    asp-fallback-src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"
                    asp-fallback-test="Windows.jQuery&& Windows.jQuery.validate&& Windows.jQuery.validate.unobtrusive"></script>
        </environment>

    </body>
</html>